version: '3.8'

services:
  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LOAD_BALANCER_URL=http://load_balancer:8001
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - load_balancer
      - redis

  load_balancer:
    build:
      context: ./load_balancer
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - SERVER_URLS=http://server1:8002,http://server2:8003
    depends_on:
      - server1
      - server2

  server1:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/testdb
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-here
      - PORT=8002
    depends_on:
      - db
      - redis

  server2:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/testdb
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-here
      - PORT=8003
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 